fix: fix user avatar
saleor/storefront pull request #1014
Opened 2023-11-11 18:11 UTC by grzegorzpokorski

Before:

![przed](https://github.com/saleor/storefront/assets/27455716/caa07569-570f-4166-b8f9-2148a8339969)

After:
1. When the user doesn't have an avatar and doesn't have defined first name (email as a fallback):

![po](https://github.com/saleor/storefront/assets/27455716/1d73a74c-1346-44f7-9441-dc4587571e2c)

2. When the user has an avatar and defined first name:

![po2](https://github.com/saleor/storefront/assets/27455716/20cbbc94-00c1-457d-846d-766077f82c93)

2023-11-12 15:05 UTC, zaiste submitted a review, later dismissed

2023-11-13 10:18 UTC, mmiszy requested changes

2023-11-13 10:18 UTC, mmiszy commented on src/ui/components/nav/components/UserMenu.tsx
> +							{data.me.email.slice(0, 2)}
We typically use initials for this. This could be a separate component because the logic quickly becomes complicated

2023-11-13 10:18 UTC, mmiszy commented on src/ui/components/nav/components/UserMenu.tsx
> +										onClick={() => signOut()}
```suggestion
										type="button"
										onClick={() => signOut()}
```

2023-11-13 13:51 UTC, zaiste approved these changes

2023-11-13 13:56 UTC, merged