fix: redesign order list
saleor/storefront pull request #1022
Opened 2023-11-14 14:53 UTC by grzegorzpokorski

Making order list design consistent with other parts of the storefront like cart.

2023-11-14 15:01 UTC, mmiszy commented
@grzegorzpokorski I've changed the base branch to `main` as we'll be going on with `main` instead of `canary` from now on.

2023-11-14 15:03 UTC, grzegorzpokorski commented
> @grzegorzpokorski I've changed the base branch to `main` as we'll be going on with `main` instead of `canary` from now on.

Thanks for information!

2023-11-15 10:37 UTC, zaiste approved these changes

2023-11-15 10:38 UTC, zaiste commented
@grzegorzpokorski looks good! Let's ship it

2023-11-15 10:45 UTC, grzegorzpokorski commented
> @grzegorzpokorski looks good! Let's ship it

Okay, but for now, I will hide the 'View Order' link until we haven't implemented the order detail page.

2023-11-15 11:37 UTC, mmiszy requested changes

2023-11-15 11:37 UTC, mmiszy commented on src/ui/components/OrderList/components/OrderListItem.tsx
> +									if (item.variant) {
Reverse the condition;
```suggestion
									if (!item.variant) {
										return null;
									}
```

2023-11-15 11:37 UTC, mmiszy commented on src/ui/components/OrderList/components/OrderListItem.tsx
> +									if (item.variant) {
Reverse the condition;
```suggestion
									if (!item.variant) {
										return null;
									}
```

2023-11-15 11:37 UTC, mmiszy commented on src/ui/components/OrderList/components/OrderListItem.tsx
> +												className="[&>td:last-child]:text-end max-md:[&>td:not(:first-child):not(:last-child)]:hidden [&>td:not(:last-child)]:pr-6 md:[&>td:not(:last-child)]:pr-6 [&>td]:py-6"
Can't we add classes to the `td`s below instead of this?

2023-11-15 11:37 UTC, mmiszy commented on src/ui/components/OrderList/components/OrderListItem.tsx
> +										const product = item.variant?.product;
```suggestion
										const product = item.variant.product;
```

2023-11-15 11:37 UTC, mmiszy commented on src/ui/components/OrderList/components/OrderListItem.tsx
> +																	{item.variant.name !== item.variant?.id && Boolean(item.variant.name)
This condition seems to be redundant to the one on line 94

2023-11-15 11:37 UTC, mmiszy commented on src/ui/components/OrderList/components/OrderListItem.tsx
> +															{item.variant.name !== item.variant?.id && Boolean(item.variant.name) && (
```suggestion
															{item.variant.name !== item.variant.id && Boolean(item.variant.name) && (
```

2023-11-15 11:37 UTC, mmiszy commented on src/ui/components/OrderList/components/OrderListItem.tsx
> +													{item.quantity} x{" "}
```suggestion
													{item.quantity} ×{" "}
```

2023-11-15 11:37 UTC, mmiszy commented on src/ui/components/OrderList/components/OrderListItem.tsx
> +																{item.quantity} x{" "}
```suggestion
																{item.quantity} ×{" "}
```

2023-11-15 11:37 UTC, mmiszy commented on src/ui/components/OrderList/components/PaymentStatus.tsx
> +					canceled
Let's settle on one spelling – either `cancelled` or `canceled` everywhere

2023-11-15 11:37 UTC, mmiszy commented on src/utils/getHrefForVariant.ts
> +export function getHrefForVariant({ productSlug, variantId }: Args): string {
```suggestion
export function getHrefForVariant({ productSlug, variantId }: { productSlug: string; variantId: string }): string {
```

2023-11-15 11:37 UTC, mmiszy commented on src/utils/getHrefForVariant.ts
> +export function getHrefForVariant({ productSlug, variantId }: Args): string {
We could make the `variantId` optional and then return the URL to the product page

2023-11-15 11:37 UTC, mmiszy commented on src/ui/components/OrderList/components/OrderListItem.tsx
> +																		: `/products/${product.slug}`
Below I've suggested to make the `variantId` in `getHrefForVariant` optional so this condition wouldn't be needed.

2023-11-15 11:37 UTC, mmiszy commented on src/ui/components/OrderList/components/OrderListItem.tsx
> +																		: `/products/${product.slug}`
Below I've suggested making the `variantId` in `getHrefForVariant` optional so this condition wouldn't be needed.

2023-11-15 13:33 UTC, grzegorzpokorski commented
@mmiszy I've implemented all suggestions.

2023-11-15 14:20 UTC, mmiszy approved these changes

2023-11-15 14:21 UTC, merged